package tmall.pojo;

import tmall.mapper.CategoryMapper;
import tmall.pojo.extension.CategoryExtension;

public class Category extends CategoryExtension implements tmall.pojo.ORM.POJOMapper<CategoryMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.recommend
     *
     * @mbg.generated
     */
    private Integer recommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.recommend
     *
     * @return the value of category.recommend
     *
     * @mbg.generated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.recommend
     *
     * @param recommend the value for category.recommend
     *
     * @mbg.generated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }
}