package tmall.pojo;

import java.math.BigDecimal;
import java.util.Date;
import tmall.mapper.OrderMapper;
import tmall.pojo.extension.OrderExtension;

public class Order extends OrderExtension implements tmall.pojo.ORM.POJOMapper<OrderMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.orderCode
     *
     * @mbg.generated
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.sum
     *
     * @mbg.generated
     */
    private BigDecimal sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.totalNumber
     *
     * @mbg.generated
     */
    private Integer totalNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.post
     *
     * @mbg.generated
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.userMessage
     *
     * @mbg.generated
     */
    private String userMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.createDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.payDate
     *
     * @mbg.generated
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.deliverDate
     *
     * @mbg.generated
     */
    private Date deliverDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.confirmDate
     *
     * @mbg.generated
     */
    private Date confirmDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.uid
     *
     * @return the value of order_.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.uid
     *
     * @param uid the value for order_.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.orderCode
     *
     * @return the value of order_.orderCode
     *
     * @mbg.generated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.orderCode
     *
     * @param orderCode the value for order_.orderCode
     *
     * @mbg.generated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.sum
     *
     * @return the value of order_.sum
     *
     * @mbg.generated
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.sum
     *
     * @param sum the value for order_.sum
     *
     * @mbg.generated
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.totalNumber
     *
     * @return the value of order_.totalNumber
     *
     * @mbg.generated
     */
    public Integer getTotalNumber() {
        return totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.totalNumber
     *
     * @param totalNumber the value for order_.totalNumber
     *
     * @mbg.generated
     */
    public void setTotalNumber(Integer totalNumber) {
        this.totalNumber = totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.address
     *
     * @return the value of order_.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.address
     *
     * @param address the value for order_.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.post
     *
     * @return the value of order_.post
     *
     * @mbg.generated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.post
     *
     * @param post the value for order_.post
     *
     * @mbg.generated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.receiver
     *
     * @return the value of order_.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.receiver
     *
     * @param receiver the value for order_.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.mobile
     *
     * @return the value of order_.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.mobile
     *
     * @param mobile the value for order_.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.userMessage
     *
     * @return the value of order_.userMessage
     *
     * @mbg.generated
     */
    public String getUserMessage() {
        return userMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.userMessage
     *
     * @param userMessage the value for order_.userMessage
     *
     * @mbg.generated
     */
    public void setUserMessage(String userMessage) {
        this.userMessage = userMessage == null ? null : userMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.createDate
     *
     * @return the value of order_.createDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.createDate
     *
     * @param createDate the value for order_.createDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.payDate
     *
     * @return the value of order_.payDate
     *
     * @mbg.generated
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.payDate
     *
     * @param payDate the value for order_.payDate
     *
     * @mbg.generated
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.deliverDate
     *
     * @return the value of order_.deliverDate
     *
     * @mbg.generated
     */
    public Date getDeliverDate() {
        return deliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.deliverDate
     *
     * @param deliverDate the value for order_.deliverDate
     *
     * @mbg.generated
     */
    public void setDeliverDate(Date deliverDate) {
        this.deliverDate = deliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.confirmDate
     *
     * @return the value of order_.confirmDate
     *
     * @mbg.generated
     */
    public Date getConfirmDate() {
        return confirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.confirmDate
     *
     * @param confirmDate the value for order_.confirmDate
     *
     * @mbg.generated
     */
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.status
     *
     * @return the value of order_.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.status
     *
     * @param status the value for order_.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}