package tmall.pojo;

import tmall.mapper.ProductImageMapper;
import tmall.pojo.extension.ProductImageExtension;

public class ProductImage extends ProductImageExtension implements tmall.pojo.ORM.POJOMapper<ProductImageMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.pid
     *
     * @return the value of product_image.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.pid
     *
     * @param pid the value for product_image.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.type
     *
     * @return the value of product_image.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.type
     *
     * @param type the value for product_image.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}