package tmall.pojo;

import tmall.mapper.UserMapper;
import tmall.pojo.extension.UserExtension;

public class User extends UserExtension implements tmall.pojo.ORM.POJOMapper<UserMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.group_
     *
     * @mbg.generated
     */
    private String group_;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.group_
     *
     * @return the value of user.group_
     *
     * @mbg.generated
     */
    public String getGroup_() {
        return group_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.group_
     *
     * @param group_ the value for user.group_
     *
     * @mbg.generated
     */
    public void setGroup_(String group_) {
        this.group_ = group_ == null ? null : group_.trim();
    }
}